import type { Metadata } from "next";
import { montserrat } from './ui/fonts';
import "./ui/styles/globals.css";
import NavLinks from "./components/nav-links";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-slate-600`}>
        <header>
          <NavLinks />
          <Footer />
        </header>
        <section>
          <div className="console-container">
            <div className="top-bar">
              <div className="window-controls"><button>x</button></div>
            </div>
            <main>
              {children}
            </main>
          </div>
        </section>
      </body>
    </html>
  );
}
