import type { Metadata } from "next";
import { montserrat } from './ui/fonts';
import "./ui/styles/globals.css";
import NavLinks from "./components/nav-links";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-slate-600`}>
        <section>
          <NavLinks />
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
